<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Access_Token extends Model
{
    protected $fillable = [
        'token',
        'user_id',
        'expire_time',
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->expire_time = now()->addMinutes(30);
        });
    }

    public function user():BelongsTo{
        return $this->belongsTo(User::class, 'user_id');
    }
}
